services:
  nginx:
    container_name: nginx
    build: ./requirements/nginx
    image: srcs-nginx
    depends_on:
      - wordpress
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - wordpress_data:/var/www/wordpress

  wordpress:
    container_name: wordpress
    build: ./requirements/wordpress
    image: srcs-wordpress
    depends_on:
      - mariadb
    ports:
      - "9000"
    volumes:
      - wordpress_data:/var/www/wordpress

  mariadb:
    container_name: mariadb
    build: ./requirements/mariadb
    image: srcs-mariadb
    ports:
      - "3306"
    volumes:
      - mariadb_data:/var/lib/mysql

volumes:
  mariadb_data:
    name: mariadb_data
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/tjun-yu/data/mariadb

  wordpress_data:
    name: wordpress_data
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/tjun-yu/data/wordpress
