services:
  nginx:
    build: ./requirements/nginx
    image: srcs-nginx
    ports:
      - "8080:80"
    depends_on:
      - wordpress
  wordpress:
    depends_on:
      - mariadb
    build: ./requirements/wordpress
    image: srcs-wordpress
    ports:
      - "9000"
  mariadb:
    build: ./requirements/mariadb
    image: srcs-mariadb
    ports:
      - "3306"
