services:
  nginx:
    image: srcs-nginx
    # build: ./requirements/nginx
    ports:
      - "8080:80"
  wordpress:
    image: srcs-wordpress
    # build: ./requirements/wordpress
    ports:
      - "9000"
