services:
  nginx:
    build: ./requirements/nginx
    image: srcs-nginx
    depends_on:
      - wordpress
    ports:
      - "8080:80"
    volumes:
      - wordpress_data:/var/www/html

  wordpress:
    build: ./requirements/wordpress
    image: srcs-wordpress
    depends_on:
      - mariadb
    ports:
      - "9000"
    volumes:
      - wordpress_data:/var/www/wordpress/

  mariadb:
    build: ./requirements/mariadb
    image: srcs-mariadb
    ports:
      - "3306"
    volumes:
      - mariadb_data:/var/lib/mysql

volumes:
  mariadb_data:
    name: mariadb_data
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/bazzite/data/mariadb

  wordpress_data:
    name: wordpress_data
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/bazzite/data/wordpress
